[project]
name = "claude-mcp-historical-weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "anthropic>=0.66.0",
    "ipykernel>=6.30.1",
    "requests>=2.32.5",
]
